name = "PkgView"
license = "MIT"
description = "A brutalist theme for developers and their code"
tags = [
    "blog",
    "minimal",
    "dark-mode",
    "technical",
    "vim",
    "vimlike",
    "vim-style",
]
min_version = "0.152.0"
